---
# Configures tinc server

- assert:
    that:
      - "tinc_build_root != none"
      - "tinc_route != none"
      - "tinc_mask != none"
      - "tinc_subnet != none"

- name: Install tinc
  apt: name=tinc,openssl state=latest update_cache=yes
  become: true

- name: Create network configuration directory
  file:
    path: "/etc/tinc/{{ tinc_netname }}"
    state: directory
  become: true

- name: Generate SSH key
  connection: local
  shell: ssh-keygen -q -t rsa -b 4096 -f {{ tinc_build_root }}/{{ ansible_hostname }} -N '' -C '{{ ansible_hostname }}'

- name: Upload SSH private key
  copy:
    src: "{{ tinc_build_root }}/{{ ansible_hostname }}"
    dest: /etc/tinc/{{ tinc_netname }}/{{ ansible_hostname }}
    mode: u+x,go-rw
  become: true

- name: Generate main configuration file
  connection: local
  template:
    src: templates/tinc.conf.j2
    dest: "{{ tinc_build_root }}/{{ ansible_hostname }}.conf"

- name: Upload main configuration file
  copy:
    src: "{{ tinc_build_root }}/{{ ansible_hostname }}.conf"
    dest: /etc/tinc/{{ tinc_netname }}/tinc.conf
    mode: u+x,go-w
  become: true

- set_fact: vpn_ip="{{ '.'.join(tinc_route.split(".")[:-1]) }}.{{ ansible_default_ipv4.address.split(".")[-1] }}"

- name: Generate script for bringing the interface up
  shell: |
    echo ifconfig \$INTERFACE {{ vpn_ip }} netmask {{ tinc_mask }} > /etc/tinc/{{ tinc_netname }}/tinc-up
  become: true

- name: Generate script for bringing the interface down
  shell: echo ifconfig \$INTERFACE down > /etc/tinc/{{ tinc_netname }}/tinc-down
  become: true

- name: Set permissions for interface scripts
  file: path='{{ item }}' mode=u+x,go-w
  with_items:
    - "/etc/tinc/{{ tinc_netname }}/tinc-up"
    - "/etc/tinc/{{ tinc_netname }}/tinc-down"
  become: true

- name: Create host configuration directory
  connection: local
  file:
    path: "{{ tinc_build_root }}/hosts"
    state: directory

- name: Generate host configuration file
  connection: local
  template:
    src: templates/tinc.host.j2
    dest: "{{ tinc_build_root }}/hosts/{{ ansible_hostname | regex_replace('[^a-zA-Z0-9_]+', '_') }}"

# the following bit is important - tinc expects keys to be in PEM format
- name: "Append public key to host configuration files"
  connection: local
  shell: ssh-keygen -f {{ ansible_hostname }}.pub -e -m pem >> "hosts/{{ ansible_hostname | regex_replace('[^a-zA-Z0-9_]+', '_') }}"
  args:
    chdir: "{{ tinc_build_root }}/"
  notify: Synchronize host configurations

- name: Start tinc daemon
  systemd: name="tinc@{{ tinc_netname }}" enabled=yes state=started daemon_reload=yes
  become: true
