---
# Configures a docker host

- name: Add HTTPS transport support to apt
  apt: name=apt-transport-https,ca-certificates,curl,gnupg2 state=latest update_cache=yes
  become: true

- name: Add dockers official GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  become: true
  args:
    warn: False

- name: Add dockers stable repository
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list
  become: true

- name: Install latest version of docker
  apt: name=docker-ce state=latest update_cache=yes
  become: true

- name: Install docker-compose
  shell: pip3 install docker-compose
  become: true
