---
- hosts: docker
  remote_user: root
  tasks:
    - name: Add HTTPS transport support to apt
      apt: name=apt-transport-https,ca-certificates,curl,gnupg2 state=latest update_cache=yes
    - name: Add dockers official GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
      args:
        warn: False
    - name: Add dockers stable repository
      template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list
    - name: Install latest version of docker
      apt: name=docker-ce state=latest update_cache=yes
    - name: Copy docker configuration
      copy: src=daemon.json dest=/etc/docker/daemon.json
    - name: Restart docker
      service: name=docker state=restarted
    - name: Install docker-compose
      shell: pip3 install docker-compose
